<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Opuntia</AssemblyName>
    <RootNamespace>Opuntia</RootNamespace>
    <OutputType>Library</OutputType>
    <LangVersion>7.3</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Description>Structural form-finding tools for Grasshopper</Description>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <FileVersion>0.2.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Helpers.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Grasshopper">
      <HintPath>C:\Program Files\Rhino 8\Plug-ins\Grasshopper\Grasshopper.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GH_IO">
      <HintPath>C:\Program Files\Rhino 8\Plug-ins\Grasshopper\GH_IO.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RhinoCommon">
      <HintPath>C:\Program Files\Rhino 8\System\RhinoCommon.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFiles="C:\Users\ac145501\AppData\Roaming\Grasshopper\Libraries\$(AssemblyName).gha" OverwriteReadOnlyFiles="true" />
  </Target>

</Project>
